version: '3.8'
services:
  db:
    image: postgres:15
    container_name: reminder
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5423:5432"
    volumes:
      - reminder_data:/var/lib/postgresql/data

volumes:
  reminder_data: